name: BuildSageMakerModel
on:
  push:
    branches: [ test ]
  pull_request:
    branches: ["main"]
    paths: [pipelines/**]

env:
  AWS_REGION: us-east-2
  SAGEMAKER_PROJECT_NAME: mars-route-opt

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  environment_definition:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: setup python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade . botocore boto3 awscli
          ls ${{ github.workspace }}
          echo "Environment value: ${{ secrets.AWS_ACCESS_KEY_ID }}"

  unit-test-python-sagemaker-pipeline:
    needs: [environment_definition]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: SETUP PYTHON
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: INSTALL PACKAGES
        run: pip3 install tox
      - name: RUN TOX
        working-directory: sagemaker/insp-and-quality-ctrl-procs
        run: tox
  
  Ejecucion pipeline:
    needs: [unit-test-python-sagemaker-pipeline]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        id: aws_creds
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::739275483428:role/GitHubAction-AssumeRoleWithAction  # Change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

      - name: Build SageMaker Pipeline
        run: |
          export SAGEMAKER_PROJECT_ID=$(aws sagemaker describe-project \
            --project-name ${{ env.SAGEMAKER_PROJECT_NAME }} \
            --query ProjectId \
            --output text)
          export SAGEMAKER_PROJECT_ARN=$(aws sagemaker describe-project \
            --project-name ${{ env.SAGEMAKER_PROJECT_NAME }} \
            --query ProjectArn \
            --output text)
          export ARTIFACT_BUCKET=sagemaker-${{ env.SAGEMAKER_PROJECT_NAME }}-${{ env.AWS_REGION }}
          export SAGEMAKER_PROJECT_NAME_ID="${{ env.SAGEMAKER_PROJECT_NAME }}"
          export SAGEMAKER_PIPELINE_ROLE_ARN=arn:aws:iam::${{ steps.aws_creds.outputs.aws-account-id }}:role/AmazonSageMakerServiceCatalogProductsUseRole
          run-pipeline --module-name pipelines.abalone.pipeline \
            --role-arn ${SAGEMAKER_PIPELINE_ROLE_ARN} \
            --tags "[{\"Key\":\"sagemaker:project-name\", \"Value\":\"${SAGEMAKER_PROJECT_NAME}\"}, {\"Key\":\"sagemaker:project-id\", \"Value\":\"${SAGEMAKER_PROJECT_ID}\"}]" \
            --kwargs "{\"region\":\"${AWS_REGION}\",\"sagemaker_project_arn\":\"${SAGEMAKER_PROJECT_ARN}\",\"role\":\"${SAGEMAKER_PIPELINE_ROLE_ARN}\",\"default_bucket\":\"${ARTIFACT_BUCKET}\",\"pipeline_name\":\"${SAGEMAKER_PROJECT_NAME_ID}\",\"model_package_group_name\":\"${SAGEMAKER_PROJECT_NAME_ID}\",\"base_job_prefix\":\"${SAGEMAKER_PROJECT_NAME_ID}\"}"
